### ISSUE TITLE
findlib: use install(1) + support DESTDIR

### ISSUE THREAD

**Issue by 0-wiz-0** [ocaml/ocamlfind#34]
The Makefiles for findlib use mkdir and cp for installing files.
Please use install(1) instead (`install -d` for directories, `install` for files, one at a time).

Also, it would be great if you could support DESTDIR. Package managers want to install into a temporary location and create the binary package from there.

So instead of
```
mkdir -p "$(prefix)$(OCAMLFIND_BIN)"
```
use
```
install -d "$(DESTDIR)$(prefix)$(OCAMLFIND_BIN)"
```
and instead of
```
cp doc/ref-man/ocamlfind.1 "$(prefix)$(OCAMLFIND_MAN)/man1"
```
use
```
install -c doc/ref-man/ocamlfind.1 "$(DESTDIR)$(prefix)$(OCAMLFIND_MAN)/man1"
```
Thanks!

**Comment by gerdstolpmann** [comment]
There is a variable `prefix` in `Makefile`.

Sorry to say that, but there is no standard for installing things.

**Comment by 0-wiz-0** [comment]
There is a difference between `prefix` and DESTDIR.
`prefix` can be hardcoded in the binary and it's fine. `DESTDIR` is only set at installation time to temporarily use a different prefix.

install(1) has the advantage that it usually atomically replaces files - cp(1) can overwrite existing files while they're still used. And it takes care of setting the permissions properly.

**Comment by dra27** [comment]
@0-wiz-0 - in this case `prefix` is an otherwise unused variable in the `Makefile`s - it behaves exactly as `DESTDIR` does.

@gerdstolpmann - it's not at the level of POSIX, but `DESTDIR` is at least part of the [GNU Coding Standards](https://www.gnu.org/prep/standards/html_node/DESTDIR.html)!

**Comment by 0-wiz-0** [comment]
@dra27 Thanks for the hint, I hadn't thought of that option.
Yes, I can use `prefix` just like `DESTDIR`, so the functionality is already there.
