### ISSUE TITLE
An error in the computation of syntax packages?

### ISSUE THREAD

**Issue by chetmurthy** [ocaml/ocamlfind#5]
In `process_pp_spec`, syntax packages are computed by taking the argument `packages` and running it thru a predicate that checks that they have a nonempty "archive" variable.  But this means that a "meta-package" that requires N other packages and doesn't have its own archive, is not selectable as a syntax package. which means that the packages it requires are not thereby selectable, either.

The fix is trivial; I can send a PR, but I include it here only for perusal.  I've also added some logging so that writers of syntax packages can debug their META files.  If you're OK with this change, I can send you a PR; I can either include or not include the logging (I think it's useful, but it's no big deal either way).

```
    * [syntax_preds] + "byte".
    *)
 
+  let candidate_packages =
+    package_deep_ancestors syntax_preds packages in
+  if verbose then begin
+    prerr_string ("Preprocessor predicates: " ^
+		  String.concat "," syntax_preds ^ "\n");
+    prerr_string ("Candidate preprocessor packages: " ^
+		  String.concat "," candidate_packages ^ "\n");
+  end ;
+
   (* One packages must now have the variable "preprocessor", usually camlp4 *)
-  let cl_pp_packages = select_pp_packages syntax_preds packages in
+  let cl_pp_packages = select_pp_packages syntax_preds candidate_packages in
   let pp_packages =
     package_deep_ancestors syntax_preds cl_pp_packages in
 
+  if verbose then begin
+    prerr_string ("Selected preprocessor packages: " ^
+		  String.concat "," pp_packages ^ "\n");
+  end ;
+
   let preprocessor_cmds =
     List.flatten
       (List.map (fun pname ->
```

**Comment by gerdstolpmann** [comment]
No, it's not an error, but intentional. Without the check on non-empty syntax archives, you could specify *any* package here, even those that have nothing to do with preprocessing. Or, in other words, the check exists to prevent the user from doing stupid things.

Wouldn't it be possible - as simple workaround - to create a package with empty archive (e.g. `ocamlc -a -o empty.cma`)?

**Comment by chetmurthy** [comment]
Perfectly satisfactory!  I had not realized one could create empty archives.  I figured ocamlc would reject and didn't even try.  And I agree with your feeling that it'd be good to prevent the user from doing stupid things *grin*.
