### ISSUE TITLE
Using `install` as `INSTALLFILE` sets the executable bit on all installed files

### ISSUE THREAD

**Issue by glondu** [ocaml/ocamlfind#59]
Discovered while updating the Debian package. As a workaround, I set `INSTALLFILE` to `cp`.

**Comment by Leonidas-from-XIV** [comment]
I can reproduce, if I `install -c INSTALL installed` then `installed` is `+x`, also on Fedora.

The `configure` script writes these unconditionally into `Makefile.config` with a fallback comment to use `cp`, maybe it would make sense use `cp` in that case.

Looks like `install` only really makes sense for executables given it has options for stripping etc, so maybe `cp` is the better choice. What do you think @gerdstolpmann?
