### ISSUE TITLE
release 1.9.7?

### ISSUE THREAD

**Issue by JasonGross** [ocaml/ocamlfind#79]
Now that #63 and #64 have been merged, could a new release be prepared and uploaded to opam?  I'd rather avoid pinning master in https://github.com/mit-plv/fiat-crypto/pull/1939#issuecomment-2338880355

**Comment by Leonidas-from-XIV** [comment]
It would be nice if we could get #72 in as well for the release, given it looks like it ready to be merged, as that will be useful to avoid packaging a forked version for Dune :-)

**Comment by gerdstolpmann** [comment]
On it.

**Comment by JasonGross** [comment]
https://opam.ocaml.org/packages/ocamlfind/ still lists 1.9.6 as the latest version...

**Comment by Leonidas-from-XIV** [comment]
There is already https://github.com/ocaml/opam-repository/pull/27253 to release 1.9.8 which supercedes 1.9.7.
